---

- name: Install borgmatic
  pip:
    name: borgmatic
    virtualenv: '{{ borg_virtual_env }}'
    virtualenv_command: virtualenv
    virtualenv_python: python3
  become: true
  become_user: '{{ borg_user }}'

- name: Ensure borgmatic config directory exists
  file:
    path: '{{ borgmatic_config_dir }}'
    state: directory
  become: true
  become_user: '{{ borg_user }}'

- name: Create borgmatic config file
  template:
    src: app.yaml.j2
    dest: '{{ borgmatic_config_dir }}/app_{{ item.name }}.yaml'
  with_items:
    - '{{ borgmatic_configs }}'
  become: true
  become_user: '{{ borg_user }}'

- name: Set acl to allow user to read locations
  acl:
    path: '{{ item.1 }}'
    entity: '{{ borg_user }}'
    permissions: r
    etype: user
    state: present
  with_subelements:
    - '{{ borgmatic_configs }}'
    - 'config.location.source_directories'

- name: Set acl default to allow user to read locations
  acl:
    path: '{{ item.1 }}'
    entity: '{{ borg_user }}'
    permissions: r
    default: true
    recursive: true
    etype: user
    state: present
  with_subelements:
    - '{{ borgmatic_configs }}'
    - 'config.location.source_directories'

- name: Cron job
  cron:
    name: '{{ item.name }}'
    user: '{{ borg_user }}'
    minute: '{{ item.minute | default(omit) }}'
    hour: '{{ item.hour | default(omit) }}'
    weekday: '{{ item.weekday | default(omit) }}'
    month: '{{ item.month | default(omit) }}'
    # yamllint disable-line rule:line-length
    job: 'PATH={{ borg_virtual_env }}/bin:$PATH {{ borg_virtual_env }}/bin/borgmatic -c {{ borgmatic_config_dir }}/app_{{ item.name }}.yaml -v 2 >> /home/{{ borg_user }}/cron.log 2>&1'
  with_items:
    - '{{ borgmatic_configs }}'
  become: true
  become_user: '{{ borg_user }}'
