---

- name: Install borgweb
  pip:
    name: 'git+{{ borgweb_repo }}'
    virtualenv: '{{ borg_virtual_env }}'
    virtualenv_command: virtualenv
    virtualenv_python: python3
  become: true
  become_user: '{{ borg_user }}'

- name: Ensure borg logs directory exists
  file:
    path: '/home/{{ borg_user }}'
    state: directory
  become: true
  become_user: '{{ borg_user }}'

- name: Configuration env for borgweb
  template:
    src: borgweb.cfg.j2
    dest: '/home/{{ borg_user }}/borgweb.cfg'
  become: true
  become_user: '{{ borg_user }}'
