---

- name: Install dependencies
  apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  with_items:
    - python3
    - python3-dev
    - python3-pip
    - python-virtualenv
    - libssl-dev
    - openssl
    - libacl1-dev
    - libacl1
    - build-essential
    - libfuse-dev
    - fuse
    - pkg-config
    - acl

- name: Ensure Borg user exists
  user: name='{{ borg_user }}'
