---

- name: Install dependencies
  apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  with_items:
    - git
    - acl
    - python3
    - python3-dev
    - python3-pip
    - python-virtualenv
    - libssl-dev
    - openssl
    - libacl1-dev
    - libacl1
    - build-essential
    - libfuse-dev
    - fuse
    - pkg-config

- name: Ensure Borg user exists
  user: name='{{ borg_user }}'

- name: Ensure Borg directory exists
  file:
    path: '{{ borg_path }}'
    state: directory
    owner: '{{ borg_user }}'
    group: '{{ borg_user }}'
    mode: 0755

- name: Install n
  become: true
  become_user: '{{ borg_user }}'
  shell: curl -L https://git.io/n-install | SHELL=/bin/bash bash -s -- -y stable
  args:
    creates: '/home/{{ borg_user }}/n/bin/n'
    executable: /bin/bash
