---

- name: Ensure virtualenv directory exists
  file:
    path: '{{ borg_virtual_env }}'
    state: directory
  become: true
  become_user: '{{ borg_user }}'

- name: Install borg
  pip:
    name: borgbackup[fuse]
    virtualenv: '{{ borg_virtual_env }}'
    virtualenv_command: virtualenv
    virtualenv_python: python3
  become: true
  become_user: '{{ borg_user }}'

- name: Borg init backup repo
  # yamllint disable-line rule:line-length
  shell: ./bin/borg init -e '{{ borg_encryption }}' /home/{{ borg_user }}/{{ item.repo }}
  args:
    chdir: '{{ borg_virtual_env }}'
    executable: /bin/bash
    creates: '/home/{{ borg_user }}/{{ item.repo }}/README'
  with_items:
    - '{{ borgmatic_configs }}'
  become: true
  become_user: '{{ borg_user }}'
