---

- name: Ensure virtualenv directory exists
  file:
    path: '{{ borg_virtual_env }}'
    state: directory
  become: true
  become_user: '{{ borg_user }}'

- name: Install borg
  pip:
    name: borgbackup[fuse]
    virtualenv: '{{ borg_virtual_env }}'
    virtualenv_command: virtualenv
    virtualenv_python: python3
  become: true
  become_user: '{{ borg_user }}'
