---

- name: Ensure virtualenv directory exists
  file:
    path: '{{ borg_virtual_env }}'
    state: directory
  become: true
  become_user: '{{ borg_user }}'

- name: Install borg
  pip:
    name: borgbackup[fuse]
    virtualenv: '{{ borg_virtual_env }}'
    virtualenv_command: virtualenv
    virtualenv_python: python3
  become: true
  become_user: '{{ borg_user }}'

- name: Borg init backup repo
  shell: ./bin/borg init -e '{{ borg_encryption }}' '{{ item.1 }}'
  args:
    chdir: '{{ borg_virtual_env }}'
    executable: /bin/bash
    creates: '{{ item.1 }}/README'
  with_subelements:
    - '{{ borgmatic_configs }}'
    - 'config.location.repositories'
  become: true
  become_user: '{{ borg_user }}'
