---

- name: Clone the git repo for Borg
  git:
    accept_hostkey: true
    repo: '{{ borg_repo }}'
    dest: '{{ borg_path }}'
    version: '{{ borg_version | default(omit) }}'
    update: '{{ borg_repo_update | default(False) }}'
  become: true
  become_user: '{{ borg_user }}'

- name: Ensure virtualenv directory exists
  file:
    path: '{{ borg_path }}/borg-env'
    state: directory
  become: true
  become_user: '{{ borg_user }}'

- name: Install requirements
  pip:
    chdir: '{{ borg_path }}'
    virtualenv: '{{ borg_path }}/borg-env'
    virtualenv_command: virtualenv
    requirements: '{{ item }}'
    virtualenv_python: python3
  with_items:
    - requirements.d/development.txt
    - requirements.d/docs.txt
    - requirements.d/fuse.txt
  become: true
  become_user: '{{ borg_user }}'
