---

- name: Borgweb service
  template:
    src: borgweb.systemd.j2
    dest: /etc/systemd/system/borgweb.service


- name: Enable Borgweb service
  systemd:
    name: borgweb
    daemon-reload: true
    enabled: true
    state: started
