---

- name: Ensure Borg user exists
  user:
    name: '{{ borg_user }}'

- name: Set acl to allow user to read locations
  acl:
    path: '{{ item.1 }}'
    entity: '{{ borg_user }}'
    permissions: r
    recursive: true
    etype: user
    state: present
  with_subelements:
    - '{{ borgmatic_configs }}'
    - 'config.location.source_directories'

- name: Set acl to allow user to read locations
  acl:
    path: '{{ item.1 }}'
    entity: '{{ borg_user }}'
    permissions: r
    default: true
    recursive: true
    etype: user
    state: present
  with_subelements:
    - '{{ borgmatic_configs }}'
    - 'config.location.source_directories'
